# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1649f9b1290e646d7486c4387182a66feedd771a70231a0adf28953bbd6f3b3b9bb9a8862128c035a47a61da1654566f311f8c7358ec56a459198645609c4fbd

test:
  secret_key_base: 4af5cff73ee0e6c2e85fc247caddcf254e88e25ab2f9d5d183efa1a969821b354fb8523a9c1a74a921da621362c3578738d6dd73271312191479662ee7dbbf91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
